export default [
  {
    index: 1,
    strength: '8.8',
    specifications: '10 * 50',
    quantity: 5000,
    unit: '个',
    msrp: undefined,
    total_msrp_include_vat: undefined,
    estimated_cost: null,
    stock_age: 3,
    estimated_arrived_date:1498520444030,
    actual_arrived_date: 1494028800000,
    location: '一号货架',
    supplier_account: '源鑫标准间工厂',
    logistic_status_definition: '现货',
  },
  {
    index: 2,
    strength: '8.8',
    specifications: '10 * 50',
    quantity: 5,
    unit: '件',
    msrp: undefined,
    total_msrp_include_vat: undefined,
    estimated_cost: null,
    stock_age: 2,
    estimated_arrived_date:1498520444030,
    actual_arrived_date: 1494028800000,
    location: '二号货架',
    supplier_account: '恒鑫标准间工厂',
    logistic_status_definition: '在途',
  },
  {
    index: 3,
    strength: '8.8',
    specifications: '10 * 50',
    quantity: 7000,
    unit: '个',
    msrp: undefined,
    total_msrp_include_vat: undefined,
    estimated_cost: null,
    stock_age: 13,
    estimated_arrived_date:1498520444030,
    actual_arrived_date: 1494028800000,
    location: '三号货架',
    supplier_account: '桦鑫标准间工厂',
    logistic_status_definition: '现货',
  }
]
